config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users
  get 'up' => 'rails/health#show', as: :rails_health_check

  authenticate :user, ->(user) { user.admin? } do
    mount SolidQueueDashboard::Engine, at: "/admin/solid-queue"
    # mount PgHero::Engine, at: '/admin/pghero'
  end

  resource :widget, only: [:show]

  draw :api_v1
  draw :admin

  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker

  match '*unmatched', to: 'pwa#not_found', via: :all,
        constraints: ->(req) { !req.path.start_with?('/rails/active_storage') }
end

app/views/layouts/partials/admin/_aside.html.erb
<div class="wrapper-menu flex-1 bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700">
  <div class="main-sidebar px-3 pb-16 pt-5 overflow-y-auto">
    <ul class="slidebar-menu text-gray-800 dark:text-gray-200">
      <li>
        <%= active_link_to '/admin', active: :exclusive, data: { turbo_prefetch: false } do %>
          <svg fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path>
          </svg>
          <span class="ml-3">Главная</span>
        <% end %>
      </li>

      <li>
        <%= active_link_to admin_chat_widgets_path, active: :exclusive, data: { turbo_prefetch: false } do %>
          <svg fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path>
          </svg>
          <span class="ml-3">Чат-виджеты</span>
        <% end %>
      </li>

      <li>
        <%= active_link_to admin_messages_path, data: { turbo_prefetch: false } do %>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
            <path d="M2.038 5.61A2.01 2.01 0 0 0 2 6v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6c0-.12-.01-.238-.03-.352l-.866.65-7.89 6.032a2 2 0 0 1-2.429 0L2.884 6.288l-.846-.677Z"/>
            <path d="M20.677 4.117A1.996 1.996 0 0 0 20 4H4c-.225 0-.44.037-.642.105l.758.607L12 10.742 19.9 4.7l.777-.583Z"/>
          </svg>
          <span class="ml-3">Сообщения</span>
        <% end %>
      </li>

      <li>
        <%= active_link_to admin_users_path, data: { turbo_prefetch: false } do %>
          <svg fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M9 6a3 3 0 11-6 0 3 3 0 016 0zM17 6a3 3 0 11-6 0 3 3 0 016 0zM12.93 17c.046-.327.07-.66.07-1a6.97 6.97 0 00-1.5-4.33A5 5 0 0119 16v1h-6.07zM6 11a5 5 0 015 5v1H1v-1a5 5 0 015-5z"></path>
          </svg>
          <span class="ml-3">Пользователи</span>
        <% end %>
      </li>

      <li>
        <%= active_link_to admin_settings_path, data: { turbo_prefetch: false } do %>
          <svg fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"></path>
          </svg>
          <span class="ml-3">Настройки</span>
        <% end %>
      </li>

      <% if current_user.admin? %>
        <li><p class="mt-7 mb-1"> for Admin</p></li>

        <li>
          <%= link_to '/admin/solid-queue', target: "_blank" do %>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
              <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M8.737 8.737a21.49 21.49 0 0 1 3.308-2.724m0 0c3.063-2.026 5.99-2.641 7.331-1.3 1.827 1.828.026 6.591-4.023 10.64-4.049 4.049-8.812 5.85-10.64 4.023-1.33-1.33-.736-4.218 1.249-7.253m6.083-6.11c-3.063-2.026-5.99-2.641-7.331-1.3-1.827 1.828-.026 6.591 4.023 10.64m3.308-9.34a21.497 21.497 0 0 1 3.308 2.724m2.775 3.386c1.985 3.035 2.579 5.923 1.248 7.253-1.336 1.337-4.245.732-7.295-1.275M14 12a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z"/>
            </svg>

            <span class="ml-3">Solid queue</span>
          <% end %>
        </li>
        <li>
          <%= active_link_to '/admin/errors', data: { turbo_prefetch: false } do %>
            <%= render Admin::IconComponent.new name: :exception, width: 24 %>
            <span class="ml-3">Errors</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="footer-sidebar"></div>
</div>

app/views/layouts/partials/admin/_header.html.erb
<nav class="nav-bar bg-white border-gray-200 dark:bg-gray-800 dark:border-gray-700">
  <div class="nav-wrapper">
    <div class="flex justify-between items-center">
      <div class="flex items-center justify-start">
        <button class="btn-menu text-gray-600 dark:text-gray-400" data-action="click->menu-btn#showMenu">
          <%= render Admin::IconComponent.new name: :menu, width: 24, klass: 'burger' %>
          <%= render Admin::IconComponent.new name: :close, width: 24, klass: 'close' %>
        </button>
        <%= link_to '/admin' do %>
          <span>Admin</span>
        <% end %>
        <div style="height: 46px;"></div>
      </div>
      <div class="flex items-center text-gray-900 dark:text-white">
        <div data-controller="dropdown" class="relative">
          <button data-action="click->dropdown#toggle" class="h-8 w-8 flex bg-red-200 dark:bg-red-500 text-gray-900 dark:text-white px-3 py-3 items-center justify-center ml-3 text-sm rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" type="button">
            <div class="uppercase"><%= current_user.email&.at(0) %></div>
          </button>

          <!-- Dropdown menu -->
          <div data-dropdown-target="menu" class="absolute overflow-hidden right-0 top-10 z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
            <div class="text-sm text-gray-900 dark:text-white">
              <%= link_to admin_user_path(current_user), class: 'block px-4 py-3 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' do %>
                <div class="font-medium truncate"><%= current_user.email %></div>
                <div><%= t("roles.#{current_user.role}") %></div>
              <% end %>
            </div>
            <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownUserAvatarButton">
              <li>
                <a href="/admin" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Аналитика</a>
              </li>
              <li>
                <a href="/admin/settings" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Настройки</a>
              </li>
            </ul>
            <%= button_to "Выйти", destroy_user_session_path, method: :delete, class: 'py-2 w-full text-left block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/partials/admin/_modal.html.erb
<div id="modal" data-controller="modal" tabindex="-1" aria-hidden="true" class="hidden flex overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative p-4 w-full max-w-3xl max-h-full">
    <!-- Modal content -->
    <div class="relative bg-white rounded-lg shadow-lg dark:bg-gray-700">
      <!-- Modal header -->
      <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
        <h3 id="modal_title" class="text-xl font-semibold text-gray-900 dark:text-white"></h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="default-modal" data-action="click->modal#close">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <!-- Modal body -->
      <div id="modal_body" class="p-4 md:p-5 space-y-4"></div>
      <!-- Modal footer -->
      <div id="modal_footer" class="text-gray-900 dark:text-white flex items-center p-4 md:p-5 border-t border-gray-200 rounded-b dark:border-gray-600">
        <div id="modal_price" class="ml-auto text-right"></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/partials/admin/_pagy.html.erb
<div class="py-4 px-6 text-gray-500 dark:text-gray-400">
  <% if @pagy.pages > 1 %>
    <div class="mb-3"><%== pagy_nav(@pagy) %></div>
  <% end %>
  <%== pagy_info(@pagy) %>
</div>