config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users
  get 'up' => 'rails/health#show', as: :rails_health_check

  authenticate :user, ->(user) { user.admin? } do
    mount SolidQueueDashboard::Engine, at: "/admin/solid-queue"
    # mount PgHero::Engine, at: '/admin/pghero'
  end

  resource :widget, only: [:show]

  draw :api_v1
  draw :admin

  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker

  match '*unmatched', to: 'pwa#not_found', via: :all,
        constraints: ->(req) { !req.path.start_with?('/rails/active_storage') }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :owned_chat_widgets, class_name: 'ChatWidget', foreign_key: 'owner_id',
                                inverse_of: :owner, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :chat_widgets, through: :memberships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum :role, { user: 0, manager: 1, moderator: 2, admin: 3 }

  def admin?
    role == 'admin'
  end

  def moderator?
    role == 'moderator'
  end

  def manager?
    role == 'manager'
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[id created_at role email]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[]
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    before_action :set_user, only: %i[edit update destroy]

    def index
      @q_users      = User.order(created_at: :desc).ransack(params[:q])
      @pagy, @users = pagy(@q_users.result)
    end

    def edit
      render turbo_stream: [
        turbo_stream.update(:modal_title, 'Редактирование пользователя'),
        turbo_stream.update(:modal_body, partial: '/admin/users/edit')
      ]
    end

    def update
      if @user.update(user_params)
        update_bonus
        render turbo_stream: [
          turbo_stream.replace(@user, partial: '/admin/users/user', locals: { user: @user }),
          success_notice(t('controller.users.update'))
        ]
      else
        error_notice(@user.errors.to_a)
      end
    end

    def destroy
      @user.destroy!
      redirect_to admin_users_path, status: :see_other, notice: t('controller.users.destroy')
    end

    private

    def update_bonus
      bonus_balance = { source: current_user, bonus_amount: params[:user][:bonus_balance], reason: :admin }
      return if params[:user][:bonus_balance].blank? || params[:user][:bonus_balance] == '0'

      @user.bonus_logs.create!(bonus_balance)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.expect(setting: %i[email])
    end
  end
end

app/views/admin/users/_edit.html.slim
= form_with model: @user, url: admin_user_path(@user), method: :patch, class: 'admin-form',
        data: { action: 'submit->modal#close' } do |form|
  .mb-5
    = form.label :email
    = form.text_field :email
  .flex.items-center
    = form.submit "Сохранить"

app/views/admin/users/_user.html.slim
tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600" id="#{dom_id user}"
  td.w-4.p-4
    .flex.items-center
      input id="checkbox-table-search-1" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
      label for="checkbox-table-search-1" class="sr-only" checkbox
  td.px-6.py-4 = user.id
  th scope="row" class="py-4 w-full max-w-44" = user.email
  td.px-6.py-4
    time data-controller="timeago" data-timeago-locale-value="ru" title="#{format_date user.created_at}" datetime="#{user.created_at.iso8601}"
      = format_date user.created_at
  td.px-6.py-4 = t("roles.#{user.role}")

  td class="flex items-center px-6 py-4"
    = link_to edit_admin_user_path(user), data: { controller: 'modal-btn', action: 'click->modal-btn#open', turbo_prefetch: false }, class: 'btn me-2' do
      = render Admin::IconComponent.new name: :edit
    = button_to admin_user_path(user), method: :delete, data: { confirm: 'Вы уверены, что хотите удалить данного пользователя?', controller: 'confirm', action: 'click->confirm#call' }, class: 'btn btn-danger' do
      = render Admin::IconComponent.new name: :trash

app/views/admin/users/index.html.slim
- content_for :title, 'Пользователи'

.pt-6.px-4
  h1 class="text-xl leading-8 font-semibold text-gray-900 dark:text-white mb-4" = yield(:title)

  = search_form_for @q_users, url: admin_users_path, method: :get, class: "max-w-md mx-auto" do |f|
    .relative
      = f.search_field :email_cont_any, class: 'block w-full p-4 pe-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
      = button_tag type: 'submit', class: 'text-white absolute end-2 bottom-2.5 font-medium rounded-lg text-sm p-2' do
        svg class="w-4 h-4 text-gray-900 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20"
          path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"

#users class="pt-6"
  div class="relative overflow-x-auto shadow-md sm:rounded-lg"
    table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400"
      thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
        tr
          th scope="col" class="p-4"
            .flex.items-center
              input id="checkbox-all-search" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
              label for="checkbox-all-search" class="sr-only" checkbox
          th scope="col" class="px-6 py-3"
            = sort_link(@q_users, :id, 'ИД', data: { turbo_prefetch: false })
          th scope="col" class="px-6 py-3"
            = sort_link(@q_users, :email, 'Почта', data: { turbo_prefetch: false })
          th scope="col" class="px-6 py-3"
            = sort_link(@q_users, :created_at, 'Дата регистрации', data: { turbo_prefetch: false })
          th scope="col" class="px-6 py-3"
            = sort_link(@q_users, :role, 'Роль', data: { turbo_prefetch: false })
          th scope="col" class="px-6 py-3" Действия

      tbody = render @users

  = render partial: '/layouts/partials/admin/pagy'