config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users
  get 'up' => 'rails/health#show', as: :rails_health_check

  authenticate :user, ->(user) { user.admin? } do
    mount SolidQueueDashboard::Engine, at: "/admin/solid-queue"
    # mount PgHero::Engine, at: '/admin/pghero'
  end

  resource :widget, only: [:show]

  draw :api_v1
  draw :admin

  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker

  match '*unmatched', to: 'pwa#not_found', via: :all,
        constraints: ->(req) { !req.path.start_with?('/rails/active_storage') }
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="ru">
<html>
  <head>
    <title><%= "#{content_for(:title).present? ? "#{content_for(:title)} | " : ''}#{settings[:app_name]&.capitalize} – Admin panel" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_stylesheet_tag 'admin' %>
    <%= vite_javascript_tag 'admin' %>
  </head>

  <body class="bg-white dark:bg-gray-900 antialiased" data-controller="menu-btn">
    <header id="header">
      <%= render '/layouts/partials/notices/notices' %>
      <%= render partial: '/layouts/partials/admin/header' %>
    </header>

    <div class="body" id="body">
      <aside id="sidebar" class="sidebar"><%= render partial: '/layouts/partials/admin/aside' %></aside>

      <div class="sidebarBackdrop" data-action="click->menu-btn#showMenu"></div>

      <div class="main-content" id="main-content" data-menu-btn-target="body">
        <main>
          <%= yield %>
        </main>

        <%= render partial: '/layouts/partials/admin/footer' %>
      </div>
    </div>

    <%= render partial: '/layouts/partials/admin/modal' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Live Chat" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= vite_client_tag %>
    <%= vite_react_refresh_tag %>
    <%= vite_stylesheet_tag 'application' %>
    <%= vite_javascript_tag 'application' %>
  </head>

  <body>
    <header id="header">
      <%= render '/layouts/partials/notices/notices' %>
      <%#= render partial: '/layouts/partials/header' %>
    </header>

    <main>
      <div class="container mx-auto px-5">
        <%= yield %>
      </div>
    </main>

    <style>
        .widget-holder {
            border-radius: 16px;
            bottom: 104px;
            right: 20px;
            height: calc(90% - 64px - 20px);
            max-height: 640px !important;
            min-height: 250px !important;
            width: 400px !important;
            box-shadow: 0 5px 40px rgba(0, 0, 0, .16);
            opacity: 1;
            will-change: transform, opacity;
            transform: translateY(0);
            overflow: hidden !important;
            position: fixed !important;
            transition: opacity 0.2s linear, transform 0.25s linear;
            z-index: 2147483000 !important;
            display: none;
        }
        .widget-holder-open {
            display: block !important;
        }

        .widget-button {
            transition: transform 0.5s;
        }

        .widget-button-close::after {
            transform: rotate(-45deg);
            background-color: #fff;
            content: ' ';
            display: inline;
            height: 24px;
            left: 24px;
            position: absolute;
            top: 12px;
            width: 2px;
        }

        .widget-button-close::before {
            transform: rotate(45deg);
            background-color: #fff;
            content: ' ';
            display: inline;
            height: 24px;
            left: 24px;
            position: absolute;
            top: 12px;
            width: 2px;
        }
    </style>
    <script>
      function toggleWidget() {
        const widget = document.querySelector('.widget-holder');
        const button = document.querySelector('.widget-button');
        widget.classList.toggle('widget-holder-open');
        if (widget.classList.contains('widget-holder-open')) {
            button.classList.add('widget-button-close');
            button.querySelector('svg').style.display = 'none';
        } else {
            button.classList.remove('widget-button-close');
            button.querySelector('svg').style.display = 'block';
        }
      }
    </script>
    <div class="widget-holder">
      <iframe
        src="<%= Rails.env.production? ? "https://#{ENV.fetch('HOST', nil)}" : 'http://localhost:3000' %>/widget?token=<%= settings[:self_chat_token] %>"
        style="height: 100% !important; width: 100% !important;"
      ></iframe>
    </div>
    <div style="position: fixed; bottom: 20px; right: 20px;">
      <button
        title="Открыть чат"
        style="border-radius: 50%; background-color: rgb(0, 173, 236); display: flex; justify-content: center; align-items: center; width: 48px; height: 48px; padding: 0px; margin: 0px; outline: none; border: none; box-shadow: none; cursor: pointer;"
        class="widget-button"
        onclick="toggleWidget()"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 31 28">
          <path fill="#FFFFFF" fill-rule="evenodd" d="M23.29 13.25V2.84c0-1.378-1.386-2.84-2.795-2.84h-17.7C1.385 0 0 1.462 0 2.84v10.41c0 1.674 1.385 3.136 2.795 2.84H5.59v5.68h.93c.04 0 .29-1.05.933-.947l3.726-4.732h9.315c1.41.296 2.795-1.166 2.795-2.84zm2.795-3.785v4.733c.348 2.407-1.756 4.558-4.658 4.732h-8.385l-1.863 1.893c.22 1.123 1.342 2.127 2.794 1.893h7.453l2.795 3.786c.623-.102.93.947.93.947h.933v-4.734h1.863c1.57.234 2.795-1.02 2.795-2.84v-7.57c0-1.588-1.225-2.84-2.795-2.84h-1.863z"></path>
        </svg>
      </button>
    </div>
  </body>
</html>